# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Premake_config = debug
  GLFW_config = debug
  Glad_config = debug
  ImGui_config = debug
  yaml_cpp_config = debug
  Guacamole_config = debug
  guac_daw_config = debug

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Premake GLFW Glad ImGui yaml-cpp Guacamole guac-daw

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: GLFW Glad ImGui Premake yaml-cpp

Premake:
ifneq (,$(Premake_config))
	@echo "==== Building Premake ($(Premake_config)) ===="
	@${MAKE} --no-print-directory -C vendor/premake -f Makefile config=$(Premake_config)
endif

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Guacamole/vendor/GLFW -f Makefile config=$(GLFW_config)
endif

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C Guacamole/vendor/Glad -f Makefile config=$(Glad_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C Guacamole/vendor/imgui -f Makefile config=$(ImGui_config)
endif

yaml-cpp:
ifneq (,$(yaml_cpp_config))
	@echo "==== Building yaml-cpp ($(yaml_cpp_config)) ===="
	@${MAKE} --no-print-directory -C Guacamole/vendor/yaml-cpp -f Makefile config=$(yaml_cpp_config)
endif

Guacamole: GLFW Glad ImGui yaml-cpp
ifneq (,$(Guacamole_config))
	@echo "==== Building Guacamole ($(Guacamole_config)) ===="
	@${MAKE} --no-print-directory -C Guacamole -f Makefile config=$(Guacamole_config)
endif

guac-daw: Guacamole GLFW Glad ImGui yaml-cpp
ifneq (,$(guac_daw_config))
	@echo "==== Building guac-daw ($(guac_daw_config)) ===="
	@${MAKE} --no-print-directory -C guac-daw -f Makefile config=$(guac_daw_config)
endif

clean:
	@${MAKE} --no-print-directory -C vendor/premake -f Makefile clean
	@${MAKE} --no-print-directory -C Guacamole/vendor/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C Guacamole/vendor/Glad -f Makefile clean
	@${MAKE} --no-print-directory -C Guacamole/vendor/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C Guacamole/vendor/yaml-cpp -f Makefile clean
	@${MAKE} --no-print-directory -C Guacamole -f Makefile clean
	@${MAKE} --no-print-directory -C guac-daw -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Premake"
	@echo "   GLFW"
	@echo "   Glad"
	@echo "   ImGui"
	@echo "   yaml-cpp"
	@echo "   Guacamole"
	@echo "   guac-daw"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"